services:
  login_listener:
      class: 'Discovery\UserBundle\EventListener\LoginListener'
      arguments: ['@security.authorization_checker', '@event_dispatcher']
      tags:
          - { name: 'kernel.event_listener', event: 'security.interactive_login', method: onSecurityInteractiveLogin }